### ISSUE TITLE
volume can't be adjusted 

### ISSUE THREAD

**Issue by xPapersheepx** [MoePlayer/APlayer#791]
我采用Meting-js，但是我发现当我的播放器所在的父元素有transform: translateY(-50%);该样式时，我无法调节播放器的音量。它将只有开和关，当我注释掉这该样式时，播放器能正常调节工作。我尝试过在https://aplayer.js.org/#/首页上添加 这个样式，同样也会出现该情况

I'm using meting-js, but when aplayer has a css which is transform: translateY(-50%), the volume just can't be adjusted, it's only zero or 100% volume. And it becomes normal when I remove this css. I can't figure it out. I try it on https://aplayer.js.org/#/ too. And the volumn still not working.

如果你也用metingjs并且碰到加载时间很久或者显示不出来的情况，很有可能是meting-js的api导致的，https://github.com/metowolf/MetingJS/issues/85 

And BTW if you are using meting-js and founds out it always time out or loading in a slow pace, it may caused by meting-js's api. 
Here to check this out https://github.com/metowolf/MetingJS/issues/85 And use the new api link.

**Comment by track23** [comment]
```css
.aplayer.aplayer-fixed .aplayer-body {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  margin: 0;
  z-index: 99;
  background: #fff;
  padding-right: 18px;
  transition: all .3s ease;
  max-width: 400px;
}
```
把   position: fixed; 改为   position: absolute;
